/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-10-25 11:13:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.chainsys.core.vo.UserProfileVO;
import com.chainsys.appplatform.web.util.SessionManager;
import java.util.Locale;
import org.json.JSONObject;

public final class PlatformTemplate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tlds/struts-bean.tld", Long.valueOf(1571995242567L));
    _jspx_dependants.put("/WEB-INF/tlds/struts-html.tld", Long.valueOf(1571995242575L));
    _jspx_dependants.put("/WEB-INF/tlds/struts-logic.tld", Long.valueOf(1571995242579L));
    _jspx_dependants.put("/WEB-INF/tlds/struts-tiles.tld", Long.valueOf(1571995242586L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.json.JSONObject");
    _jspx_imports_classes.add("com.chainsys.appplatform.web.util.SessionManager");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("com.chainsys.core.vo.UserProfileVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fid_005fclassname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fscope_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg0_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fscope_005fname_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fid_005fclassname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fscope_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg0_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fscope_005fname_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fid_005fclassname_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fscope_005fname.release();
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg0_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody.release();
    _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fscope_005fname_005fid.release();
    _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  tiles:useAttribute
      org.apache.struts.tiles.taglib.UseAttributeTag _jspx_th_tiles_005fuseAttribute_005f0 = (org.apache.struts.tiles.taglib.UseAttributeTag) _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fid_005fclassname_005fnobody.get(org.apache.struts.tiles.taglib.UseAttributeTag.class);
      boolean _jspx_th_tiles_005fuseAttribute_005f0_reused = false;
      try {
        _jspx_th_tiles_005fuseAttribute_005f0.setPageContext(_jspx_page_context);
        _jspx_th_tiles_005fuseAttribute_005f0.setParent(null);
        // /jsp/templates/PlatformTemplate.jsp(11,0) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f0.setId("windowTitleKey");
        // /jsp/templates/PlatformTemplate.jsp(11,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f0.setName("window.title.key");
        // /jsp/templates/PlatformTemplate.jsp(11,0) name = classname type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_tiles_005fuseAttribute_005f0.setClassname("java.lang.String");
        int _jspx_eval_tiles_005fuseAttribute_005f0 = _jspx_th_tiles_005fuseAttribute_005f0.doStartTag();
        if (_jspx_th_tiles_005fuseAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ftiles_005fuseAttribute_0026_005fname_005fid_005fclassname_005fnobody.reuse(_jspx_th_tiles_005fuseAttribute_005f0);
        _jspx_th_tiles_005fuseAttribute_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005fuseAttribute_005f0, _jsp_getInstanceManager(), _jspx_th_tiles_005fuseAttribute_005f0_reused);
      }
      java.lang.String windowTitleKey = null;
      windowTitleKey = (java.lang.String) _jspx_page_context.findAttribute("windowTitleKey");
      out.write(' ');
      out.write('\r');
      out.write('\n');
 SessionManager sessionManager = SessionManager.getInstance(request,response);
JSONObject loggedUserApp = new JSONObject(pageContext.getSession().getAttribute("LOGGED_USER_APPLICATIONS").toString());
String  applicationId = pageContext.getSession().getAttribute("CURRENT_APPLICATION_ID").toString();
JSONObject applicationDetails = new JSONObject(loggedUserApp .getString(String.valueOf(applicationId).toString()));
String appShortCode = applicationDetails.getString("appShortCode");
UserProfileVO profileVO = (UserProfileVO)sessionManager.getAttribute("USER_PROFILE");
if(profileVO == null){ 
    response.sendRedirect(request.getContextPath());
    return;
}
Locale locale = profileVO.getUserLocale();
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("\t\t<title>Chainsys Platform</title>\r\n");
      out.write("\t\t<link href=\"../css/cs-app-icons.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"../css/cs-app-tile.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"../css/cs-plugins.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"../css/cs-common.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link href=\"../css/cs-allapi.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t\t<link rel=\"icon\" href=\"../images/csbase/favicon.ico\" type=\"image/x-icon\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/templates/AppJSImport.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t<script src=\"../js/core/applicationlogs.js\"></script>\r\n");
      out.write("\t\t<script src=\"../js/plugins/jquery-popover.js\"></script>\r\n");
      out.write("\t\t<script src=\"../js/jquery/jquery.cookie.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"cs-default-theme cs-menu-grid\">\r\n");
      out.write("\t\t");

			org.apache.struts.util.PropertyMessageResources p=(org.apache.struts.util.PropertyMessageResources)pageContext.getServletContext().getAttribute(org.apache.struts.Globals.MESSAGES_KEY);
			pageContext.setAttribute(org.apache.struts.Globals.MESSAGES_KEY, p,PageContext.REQUEST_SCOPE);
	   
      out.write("\r\n");
      out.write("\t\t<div id=\"modalLayer\" class=\"LayerClass cs-ant-modalLayer\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  \t<div class=\"cs-container-fluid clearfix\">\r\n");
      out.write("\t\t\t<div  id=\"cs-wrapper\" class=\"cs-wrapper cs-row-fluid\">\r\n");
      out.write("\t\t\t    <header class=\"cs-header\">\r\n");
      out.write("\t\t\t    \t");
      if (_jspx_meth_tiles_005finsert_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t    </header>\r\n");
      out.write("\t\t\t    <main class=\"clearfix\">\r\n");
      out.write("\t\t\t\t    <aside class=\"cs-side-menu\">\r\n");
      out.write("\t\t\t\t         ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/templates/AppMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t    </aside>\r\n");
      out.write("\t\t\t\t    <section class=\"cs-main-content cs-pr\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"cs-page-head\">\r\n");
      out.write("\t\t\t\t          <h2 class=\"cs-pull-left cs-cf-pagehead-left cs-headerselect cs-flex cs-column-middle\">\r\n");
      out.write("\t\t\t\t\t           <span class=\"cs-pagename\">\r\n");
      out.write("\t\t\t\t\t\t           ");
 if (windowTitleKey !=null && windowTitleKey !="") { 
      out.write(" \t \t\t\t        \t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      //  bean:message
      org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
      boolean _jspx_th_bean_005fmessage_005f0_reused = false;
      try {
        _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
        _jspx_th_bean_005fmessage_005f0.setParent(null);
        // /jsp/templates/PlatformTemplate.jsp(60,10) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fmessage_005f0.setKey( windowTitleKey );
        // /jsp/templates/PlatformTemplate.jsp(60,10) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_bean_005fmessage_005f0.setLocale(locale.getLanguage());
        int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
        if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
        _jspx_th_bean_005fmessage_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t ");
}
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t          <div class=\"cs-cell-10 cs-action-block cs-btn-group cs-flex cs-column-middle\" id =\"bodyTopButtons\">\r\n");
      out.write("\t\t\t\t          \t<div class='cs-btn-group cs-hmar cs-inline' id=\"navigationButtons\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t          </div>\r\n");
      out.write("\t\t\t\t          <!-- <div class=\"cs-modulestatus cs-pull-right\"></div>-->\r\n");
      out.write("\t\t\t\t        </div> \r\n");
      out.write("\t\t\t\t       <div class='cs-cell-24f cs-flex cs-center'>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cs-dec-details cs-hide cs-flex cs-line cs-pa\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cs-infomessage\" id=\"cs-infomessage\" contenteditable=\"false\" style=\"text-align: center\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t        <div id=\"cs-pageBody\" class=\"cs-dashboard-height cs-scroll cs-pr\">\r\n");
      out.write("\t\t\t\t         \t");
      //  logic:notEmpty
      org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f0 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fscope_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
      boolean _jspx_th_logic_005fnotEmpty_005f0_reused = false;
      try {
        _jspx_th_logic_005fnotEmpty_005f0.setPageContext(_jspx_page_context);
        _jspx_th_logic_005fnotEmpty_005f0.setParent(null);
        // /jsp/templates/PlatformTemplate.jsp(76,14) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fnotEmpty_005f0.setScope("request");
        // /jsp/templates/PlatformTemplate.jsp(76,14) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_logic_005fnotEmpty_005f0.setName("TRNMESSAGE");
        int _jspx_eval_logic_005fnotEmpty_005f0 = _jspx_th_logic_005fnotEmpty_005f0.doStartTag();
        if (_jspx_eval_logic_005fnotEmpty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            //  bean:define
            org.apache.struts.taglib.bean.DefineTag _jspx_th_bean_005fdefine_005f0 = (org.apache.struts.taglib.bean.DefineTag) _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody.get(org.apache.struts.taglib.bean.DefineTag.class);
            boolean _jspx_th_bean_005fdefine_005f0_reused = false;
            try {
              _jspx_th_bean_005fdefine_005f0.setPageContext(_jspx_page_context);
              _jspx_th_bean_005fdefine_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
              // /jsp/templates/PlatformTemplate.jsp(77,8) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_bean_005fdefine_005f0.setId("message");
              // /jsp/templates/PlatformTemplate.jsp(77,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_bean_005fdefine_005f0.setName("TRNMESSAGE");
              // /jsp/templates/PlatformTemplate.jsp(77,8) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_bean_005fdefine_005f0.setType("com.chainsys.appplatform.vo.MessageVO");
              int _jspx_eval_bean_005fdefine_005f0 = _jspx_th_bean_005fdefine_005f0.doStartTag();
              if (_jspx_th_bean_005fdefine_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody.reuse(_jspx_th_bean_005fdefine_005f0);
              _jspx_th_bean_005fdefine_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fdefine_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fdefine_005f0_reused);
            }
            com.chainsys.appplatform.vo.MessageVO message = null;
            message = (com.chainsys.appplatform.vo.MessageVO) _jspx_page_context.findAttribute("message");
            out.write("\t\r\n");
            out.write("\t\t\t\t\t\t\t\t<script>\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t     $(document).ready(function(){alertMessage('");
            //  logic:notEmpty
            org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f1 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
            boolean _jspx_th_logic_005fnotEmpty_005f1_reused = false;
            try {
              _jspx_th_logic_005fnotEmpty_005f1.setPageContext(_jspx_page_context);
              _jspx_th_logic_005fnotEmpty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
              // /jsp/templates/PlatformTemplate.jsp(79,56) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f1.setName("message");
              // /jsp/templates/PlatformTemplate.jsp(79,56) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f1.setProperty("code");
              int _jspx_eval_logic_005fnotEmpty_005f1 = _jspx_th_logic_005fnotEmpty_005f1.doStartTag();
              if (_jspx_eval_logic_005fnotEmpty_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  //  bean:message
                  org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f1 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg0_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
                  boolean _jspx_th_bean_005fmessage_005f1_reused = false;
                  try {
                    _jspx_th_bean_005fmessage_005f1.setPageContext(_jspx_page_context);
                    _jspx_th_bean_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f1);
                    // /jsp/templates/PlatformTemplate.jsp(79,103) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f1.setLocale(locale.getLanguage());
                    // /jsp/templates/PlatformTemplate.jsp(79,103) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f1.setKey("key.error."+message.getCode() );
                    // /jsp/templates/PlatformTemplate.jsp(79,103) name = arg0 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f1.setArg0(message.getArg1());
                    // /jsp/templates/PlatformTemplate.jsp(79,103) name = arg2 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f1.setArg2(message.getArg3());
                    // /jsp/templates/PlatformTemplate.jsp(79,103) name = arg3 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f1.setArg3(message.getArg4());
                    // /jsp/templates/PlatformTemplate.jsp(79,103) name = arg4 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f1.setArg4(message.getArg5());
                    int _jspx_eval_bean_005fmessage_005f1 = _jspx_th_bean_005fmessage_005f1.doStartTag();
                    if (_jspx_th_bean_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg0_005fnobody.reuse(_jspx_th_bean_005fmessage_005f1);
                    _jspx_th_bean_005fmessage_005f1_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f1_reused);
                  }
                  int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_logic_005fnotEmpty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f1);
              _jspx_th_logic_005fnotEmpty_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f1, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f1_reused);
            }
            //  logic:empty
            org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f0 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
            boolean _jspx_th_logic_005fempty_005f0_reused = false;
            try {
              _jspx_th_logic_005fempty_005f0.setPageContext(_jspx_page_context);
              _jspx_th_logic_005fempty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
              // /jsp/templates/PlatformTemplate.jsp(79,336) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fempty_005f0.setName("message");
              // /jsp/templates/PlatformTemplate.jsp(79,336) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fempty_005f0.setProperty("code");
              int _jspx_eval_logic_005fempty_005f0 = _jspx_th_logic_005fempty_005f0.doStartTag();
              if (_jspx_eval_logic_005fempty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  //  bean:message
                  org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f2 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
                  boolean _jspx_th_bean_005fmessage_005f2_reused = false;
                  try {
                    _jspx_th_bean_005fmessage_005f2.setPageContext(_jspx_page_context);
                    _jspx_th_bean_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fempty_005f0);
                    // /jsp/templates/PlatformTemplate.jsp(79,380) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f2.setLocale(locale.getLanguage());
                    // /jsp/templates/PlatformTemplate.jsp(79,380) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f2.setKey(message.getMessage() );
                    // /jsp/templates/PlatformTemplate.jsp(79,380) name = arg0 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f2.setArg0(message.getArg1());
                    // /jsp/templates/PlatformTemplate.jsp(79,380) name = arg1 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f2.setArg1(message.getArg2());
                    // /jsp/templates/PlatformTemplate.jsp(79,380) name = arg2 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f2.setArg2(message.getArg3());
                    // /jsp/templates/PlatformTemplate.jsp(79,380) name = arg3 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f2.setArg3(message.getArg4());
                    // /jsp/templates/PlatformTemplate.jsp(79,380) name = arg4 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_bean_005fmessage_005f2.setArg4(message.getArg5());
                    int _jspx_eval_bean_005fmessage_005f2 = _jspx_th_bean_005fmessage_005f2.doStartTag();
                    if (_jspx_th_bean_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody.reuse(_jspx_th_bean_005fmessage_005f2);
                    _jspx_th_bean_005fmessage_005f2_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f2_reused);
                  }
                  int evalDoAfterBody = _jspx_th_logic_005fempty_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_logic_005fempty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f0);
              _jspx_th_logic_005fempty_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f0_reused);
            }
            out.write("',\"\",'");
            if (_jspx_meth_bean_005fwrite_005f0(_jspx_th_logic_005fnotEmpty_005f0, _jspx_page_context))
              return;
            out.write("',!0,\"\",'");
            //  logic:notEmpty
            org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f2 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fscope_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
            boolean _jspx_th_logic_005fnotEmpty_005f2_reused = false;
            try {
              _jspx_th_logic_005fnotEmpty_005f2.setPageContext(_jspx_page_context);
              _jspx_th_logic_005fnotEmpty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
              // /jsp/templates/PlatformTemplate.jsp(79,687) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f2.setScope("request");
              // /jsp/templates/PlatformTemplate.jsp(79,687) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_logic_005fnotEmpty_005f2.setName("TRNMESSAGELIST");
              int _jspx_eval_logic_005fnotEmpty_005f2 = _jspx_th_logic_005fnotEmpty_005f2.doStartTag();
              if (_jspx_eval_logic_005fnotEmpty_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("<ul class=\"cs-list-unstyled cs-vmar\">");
                  //  logic:iterate
                  org.apache.struts.taglib.logic.IterateTag _jspx_th_logic_005fiterate_005f0 = (org.apache.struts.taglib.logic.IterateTag) _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fscope_005fname_005fid.get(org.apache.struts.taglib.logic.IterateTag.class);
                  boolean _jspx_th_logic_005fiterate_005f0_reused = false;
                  try {
                    _jspx_th_logic_005fiterate_005f0.setPageContext(_jspx_page_context);
                    _jspx_th_logic_005fiterate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f2);
                    // /jsp/templates/PlatformTemplate.jsp(79,778) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fiterate_005f0.setId("messageVO");
                    // /jsp/templates/PlatformTemplate.jsp(79,778) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fiterate_005f0.setName("TRNMESSAGELIST");
                    // /jsp/templates/PlatformTemplate.jsp(79,778) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fiterate_005f0.setType("com.chainsys.appplatform.vo.MessageVO");
                    // /jsp/templates/PlatformTemplate.jsp(79,778) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                    _jspx_th_logic_005fiterate_005f0.setScope("request");
                    int _jspx_eval_logic_005fiterate_005f0 = _jspx_th_logic_005fiterate_005f0.doStartTag();
                    if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                      com.chainsys.appplatform.vo.MessageVO messageVO = null;
                      if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_logic_005fiterate_005f0);
                      }
                      messageVO = (com.chainsys.appplatform.vo.MessageVO) _jspx_page_context.findAttribute("messageVO");
                      do {
                        out.write("<li>\t\t\t\t\t\t\t\t\t\t    \t\t\t");
                        if (_jspx_meth_logic_005fequal_005f0(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                          return;
                        out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t");
                        if (_jspx_meth_logic_005fequal_005f1(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                          return;
                        out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t");
                        if (_jspx_meth_logic_005fequal_005f2(_jspx_th_logic_005fiterate_005f0, _jspx_page_context))
                          return;
                        out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t");
                        //  logic:notEmpty
                        org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f3 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
                        boolean _jspx_th_logic_005fnotEmpty_005f3_reused = false;
                        try {
                          _jspx_th_logic_005fnotEmpty_005f3.setPageContext(_jspx_page_context);
                          _jspx_th_logic_005fnotEmpty_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
                          // /jsp/templates/PlatformTemplate.jsp(79,1470) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fnotEmpty_005f3.setName("messageVO");
                          // /jsp/templates/PlatformTemplate.jsp(79,1470) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fnotEmpty_005f3.setProperty("code");
                          int _jspx_eval_logic_005fnotEmpty_005f3 = _jspx_th_logic_005fnotEmpty_005f3.doStartTag();
                          if (_jspx_eval_logic_005fnotEmpty_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            do {
                              out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t\t");
                              //  bean:message
                              org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f3 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
                              boolean _jspx_th_bean_005fmessage_005f3_reused = false;
                              try {
                              _jspx_th_bean_005fmessage_005f3.setPageContext(_jspx_page_context);
                              _jspx_th_bean_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f3);
                              // /jsp/templates/PlatformTemplate.jsp(79,1537) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f3.setLocale(locale.getLanguage());
                              // /jsp/templates/PlatformTemplate.jsp(79,1537) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f3.setKey("key.error."+messageVO.getCode() );
                              // /jsp/templates/PlatformTemplate.jsp(79,1537) name = arg0 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f3.setArg0(messageVO.getArg1());
                              // /jsp/templates/PlatformTemplate.jsp(79,1537) name = arg1 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f3.setArg1(messageVO.getArg2());
                              // /jsp/templates/PlatformTemplate.jsp(79,1537) name = arg2 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f3.setArg2(messageVO.getArg3());
                              // /jsp/templates/PlatformTemplate.jsp(79,1537) name = arg3 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f3.setArg3(messageVO.getArg4());
                              // /jsp/templates/PlatformTemplate.jsp(79,1537) name = arg4 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f3.setArg4(messageVO.getArg5());
                              int _jspx_eval_bean_005fmessage_005f3 = _jspx_th_bean_005fmessage_005f3.doStartTag();
                              if (_jspx_th_bean_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody.reuse(_jspx_th_bean_005fmessage_005f3);
                              _jspx_th_bean_005fmessage_005f3_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f3_reused);
                              }
                              out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t");
                              int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f3.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_logic_005fnotEmpty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f3);
                          _jspx_th_logic_005fnotEmpty_005f3_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f3, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f3_reused);
                        }
                        out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t");
                        //  logic:empty
                        org.apache.struts.taglib.logic.EmptyTag _jspx_th_logic_005fempty_005f1 = (org.apache.struts.taglib.logic.EmptyTag) _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.EmptyTag.class);
                        boolean _jspx_th_logic_005fempty_005f1_reused = false;
                        try {
                          _jspx_th_logic_005fempty_005f1.setPageContext(_jspx_page_context);
                          _jspx_th_logic_005fempty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
                          // /jsp/templates/PlatformTemplate.jsp(79,1953) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fempty_005f1.setName("messageVO");
                          // /jsp/templates/PlatformTemplate.jsp(79,1953) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                          _jspx_th_logic_005fempty_005f1.setProperty("code");
                          int _jspx_eval_logic_005fempty_005f1 = _jspx_th_logic_005fempty_005f1.doStartTag();
                          if (_jspx_eval_logic_005fempty_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                            do {
                              out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t\t");
                              //  bean:message
                              org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f4 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
                              boolean _jspx_th_bean_005fmessage_005f4_reused = false;
                              try {
                              _jspx_th_bean_005fmessage_005f4.setPageContext(_jspx_page_context);
                              _jspx_th_bean_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fempty_005f1);
                              // /jsp/templates/PlatformTemplate.jsp(79,2017) name = locale type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f4.setLocale(locale.getLanguage());
                              // /jsp/templates/PlatformTemplate.jsp(79,2017) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f4.setKey(messageVO.getMessage() );
                              // /jsp/templates/PlatformTemplate.jsp(79,2017) name = arg0 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f4.setArg0(messageVO.getArg1());
                              // /jsp/templates/PlatformTemplate.jsp(79,2017) name = arg1 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f4.setArg1(messageVO.getArg2());
                              // /jsp/templates/PlatformTemplate.jsp(79,2017) name = arg2 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f4.setArg2(messageVO.getArg3());
                              // /jsp/templates/PlatformTemplate.jsp(79,2017) name = arg3 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f4.setArg3(messageVO.getArg4());
                              // /jsp/templates/PlatformTemplate.jsp(79,2017) name = arg4 type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                              _jspx_th_bean_005fmessage_005f4.setArg4(messageVO.getArg5());
                              int _jspx_eval_bean_005fmessage_005f4 = _jspx_th_bean_005fmessage_005f4.doStartTag();
                              if (_jspx_th_bean_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                              return;
                              }
                              _005fjspx_005ftagPool_005fbean_005fmessage_0026_005flocale_005fkey_005farg4_005farg3_005farg2_005farg1_005farg0_005fnobody.reuse(_jspx_th_bean_005fmessage_005f4);
                              _jspx_th_bean_005fmessage_005f4_reused = true;
                              } finally {
                              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_bean_005fmessage_005f4_reused);
                              }
                              out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t");
                              int evalDoAfterBody = _jspx_th_logic_005fempty_005f1.doAfterBody();
                              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                              break;
                            } while (true);
                          }
                          if (_jspx_th_logic_005fempty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                            return;
                          }
                          _005fjspx_005ftagPool_005flogic_005fempty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fempty_005f1);
                          _jspx_th_logic_005fempty_005f1_reused = true;
                        } finally {
                          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fempty_005f1, _jsp_getInstanceManager(), _jspx_th_logic_005fempty_005f1_reused);
                        }
                        out.write("\t\t\t\t\t\t\t\t\t\t    \t\t</li>\t\t\t\t\t\t\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t    \t");
                        int evalDoAfterBody = _jspx_th_logic_005fiterate_005f0.doAfterBody();
                        messageVO = (com.chainsys.appplatform.vo.MessageVO) _jspx_page_context.findAttribute("messageVO");
                        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                          break;
                      } while (true);
                      if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                        out = _jspx_page_context.popBody();
                      }
                    }
                    if (_jspx_th_logic_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005ftype_005fscope_005fname_005fid.reuse(_jspx_th_logic_005fiterate_005f0);
                    _jspx_th_logic_005fiterate_005f0_reused = true;
                  } finally {
                    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fiterate_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fiterate_005f0_reused);
                  }
                  out.write("\t\t\t      \t\t\t\t\t\t\t\t\t\t    </ul>\t\t\t\t\t\t\t\t\t\t  \t\t\t\t\t\t\t\t\t  ");
                  int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_logic_005fnotEmpty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fscope_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f2);
              _jspx_th_logic_005fnotEmpty_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f2, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f2_reused);
            }
            out.write("')});\r\n");
            out.write("\t\t\t\t\t\t\t\t</script>\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_logic_005fnotEmpty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fscope_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f0);
        _jspx_th_logic_005fnotEmpty_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fnotEmpty_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fnotEmpty_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t   \t\t \t");
      if (_jspx_meth_tiles_005finsert_005f1(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t   \t   </div>\r\n");
      out.write("\t\t\t\t    </section>\r\n");
      out.write("\t\t\t    </main>\r\n");
      out.write("\t\t      </div>\r\n");
      out.write("\t\t  \t  <div id=\"cs-dropdown-3\" class=\"cs-dropdown cs-dropdown-anchor-right\">\r\n");
      out.write("\t\t\t\t<ul class=\"cs-dropdown-menu\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t \t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar dummySubmit;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function(){\t\r\n");
      out.write("\t\t\tfunction visWinheight () {\r\n");
      out.write("\t\t\t\tvar visBody = $(window).height();\r\n");
      out.write("\t\t\t\tvar visHeader = $(\"header\").outerHeight();\r\n");
      out.write("\t\t\t\tvar vispageHead = $(\".cs-page-head\").outerHeight();\r\n");
      out.write("\t\t\t\tvar visFooter = $(\"footer\").outerHeight();\r\n");
      out.write("\t\t\t\t$(\".vis-window-height\").height(visBody - visHeader - vispageHead - visFooter + 11 + \"px\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(window).resize(function() { \r\n");
      out.write("\t\t\t\tvisWinheight(); \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar appShortCode = '");
      out.print(appShortCode);
      out.write("';\r\n");
      out.write("\t\t   \tif(appShortCode == \"APPD\")\r\n");
      out.write("\t\t   \t   $('#cs-pageBody').removeClass('cs-dashboard-height cs-scroll cs-pr');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t    if ($.cookie('crumblink') !== undefined) {\r\n");
      out.write("\t\t\tdocument.getElementById('breadcrumb').innerHTML = $.cookie('crumblink');\r\n");
      out.write("\t\t\t$.removeCookie('crumblink');\r\n");
      out.write("    \t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction applicationLaunch(appId,appShortCode,appType) { \r\n");
      out.write("\t\t    $.ajax({ \r\n");
      out.write("\t\t\t    type : \"POST\",\r\n");
      out.write("\t\t\t    dataType : \"text\", \r\n");
      out.write("\t\t\t    url : PFM_CONTEXT_PATH + \"/core/ApplicationSwitchAjaxMapping.echn\", \r\n");
      out.write("\t\t\t    data : {\"currentAppId\":appId}, \r\n");
      out.write("\t\t\t    success : function(data) { \r\n");
      out.write("\t\t\t    \tif(data=='Y' && appType != undefined && appType !='MOBILE' && appShortCode!='ABLD') {\r\n");
      out.write("\t\t\t\t   \t\t document.location.href= PFM_CONTEXT_PATH + '/core/ApplicationSwitcher.echn'; \r\n");
      out.write("\t\t\t\t   \t }else if (data == 'Y' && appType == 'MOBILE') {\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/appdesigner/OrgDeploymentMapping.echn\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"appId\" : appId\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar data = JSON.parse(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar param = data.param;  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t   OpenWindowWithPost(data.URL+\"/switcher\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \"width=730,height=345,left=100,top=100,resizable=yes,scrollbars=yes\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   \"NewFile\", param);   \r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}else if (data == 'Y' && appShortCode == 'ABLD') {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/appdesigner/switchAppBuilderMapping.echn\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\twindow.open(data, \"_self\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t  \t } \r\n");
      out.write("\t\t    }); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction fetchOrganizationDetails() {\r\n");
      out.write("\t\t\tlocation.href = PFM_CONTEXT_PATH\r\n");
      out.write("\t\t\t\t\t+ \"/appdesigner/OrganizationForm.echn?action=lanuch\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction OpenWindowWithPost(url, windowoption, name, params) {\r\n");
      out.write("\t           var form = document.createElement(\"form\");\r\n");
      out.write("\t           form.setAttribute(\"method\", \"post\");\r\n");
      out.write("\t           form.setAttribute(\"action\", url);\r\n");
      out.write("\t           form.setAttribute(\"target\", \"_blank\");\r\n");
      out.write("\t           for (var i in params) {\r\n");
      out.write("\t               if (params.hasOwnProperty(i)) {\r\n");
      out.write("\t                   var input = document.createElement('input');\r\n");
      out.write("\t                   input.type = 'hidden';\r\n");
      out.write("\t                   input.name = i;\r\n");
      out.write("\t                   input.value = params[i];\r\n");
      out.write("\t                   form.appendChild(input);\r\n");
      out.write("\t               }\r\n");
      out.write("\t           }\r\n");
      out.write("\t           document.body.appendChild(form);\r\n");
      out.write("\t           form.submit();       \r\n");
      out.write("\t           document.body.removeChild(form);\r\n");
      out.write("\t}\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsert_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.tiles.taglib.InsertTag _jspx_th_tiles_005finsert_005f0 = (org.apache.struts.tiles.taglib.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.get(org.apache.struts.tiles.taglib.InsertTag.class);
    boolean _jspx_th_tiles_005finsert_005f0_reused = false;
    try {
      _jspx_th_tiles_005finsert_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsert_005f0.setParent(null);
      // /jsp/templates/PlatformTemplate.jsp(49,8) name = attribute type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsert_005f0.setAttribute("app.header");
      int _jspx_eval_tiles_005finsert_005f0 = _jspx_th_tiles_005finsert_005f0.doStartTag();
      if (_jspx_th_tiles_005finsert_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f0);
      _jspx_th_tiles_005finsert_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsert_005f0, _jsp_getInstanceManager(), _jspx_th_tiles_005finsert_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_bean_005fwrite_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotEmpty_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:write
    org.apache.struts.taglib.bean.WriteTag _jspx_th_bean_005fwrite_005f0 = (org.apache.struts.taglib.bean.WriteTag) _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.get(org.apache.struts.taglib.bean.WriteTag.class);
    boolean _jspx_th_bean_005fwrite_005f0_reused = false;
    try {
      _jspx_th_bean_005fwrite_005f0.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fwrite_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
      // /jsp/templates/PlatformTemplate.jsp(79,634) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setName("message");
      // /jsp/templates/PlatformTemplate.jsp(79,634) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fwrite_005f0.setProperty("type");
      int _jspx_eval_bean_005fwrite_005f0 = _jspx_th_bean_005fwrite_005f0.doStartTag();
      if (_jspx_th_bean_005fwrite_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fbean_005fwrite_0026_005fproperty_005fname_005fnobody.reuse(_jspx_th_bean_005fwrite_005f0);
      _jspx_th_bean_005fwrite_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_bean_005fwrite_005f0, _jsp_getInstanceManager(), _jspx_th_bean_005fwrite_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fequal_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:equal
    org.apache.struts.taglib.logic.EqualTag _jspx_th_logic_005fequal_005f0 = (org.apache.struts.taglib.logic.EqualTag) _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.get(org.apache.struts.taglib.logic.EqualTag.class);
    boolean _jspx_th_logic_005fequal_005f0_reused = false;
    try {
      _jspx_th_logic_005fequal_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fequal_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /jsp/templates/PlatformTemplate.jsp(79,912) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f0.setName("messageVO");
      // /jsp/templates/PlatformTemplate.jsp(79,912) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f0.setProperty("type");
      // /jsp/templates/PlatformTemplate.jsp(79,912) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f0.setValue("INFO");
      int _jspx_eval_logic_005fequal_005f0 = _jspx_th_logic_005fequal_005f0.doStartTag();
      if (_jspx_eval_logic_005fequal_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t\t<i class=\"fa fa-check-circle cs-ts-14\"></i>\t\t\t\t\t\t\t\t\t\t    \t\t\t");
          int evalDoAfterBody = _jspx_th_logic_005fequal_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fequal_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.reuse(_jspx_th_logic_005fequal_005f0);
      _jspx_th_logic_005fequal_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fequal_005f0, _jsp_getInstanceManager(), _jspx_th_logic_005fequal_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fequal_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:equal
    org.apache.struts.taglib.logic.EqualTag _jspx_th_logic_005fequal_005f1 = (org.apache.struts.taglib.logic.EqualTag) _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.get(org.apache.struts.taglib.logic.EqualTag.class);
    boolean _jspx_th_logic_005fequal_005f1_reused = false;
    try {
      _jspx_th_logic_005fequal_005f1.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fequal_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /jsp/templates/PlatformTemplate.jsp(79,1080) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f1.setName("messageVO");
      // /jsp/templates/PlatformTemplate.jsp(79,1080) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f1.setProperty("type");
      // /jsp/templates/PlatformTemplate.jsp(79,1080) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f1.setValue("WARNING");
      int _jspx_eval_logic_005fequal_005f1 = _jspx_th_logic_005fequal_005f1.doStartTag();
      if (_jspx_eval_logic_005fequal_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t\t<i class=\"fa  fa-warning cs-ts-14\"></i>\t\t\t\t\t\t\t\t\t\t    \t\t\t");
          int evalDoAfterBody = _jspx_th_logic_005fequal_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fequal_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.reuse(_jspx_th_logic_005fequal_005f1);
      _jspx_th_logic_005fequal_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fequal_005f1, _jsp_getInstanceManager(), _jspx_th_logic_005fequal_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_logic_005fequal_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fiterate_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:equal
    org.apache.struts.taglib.logic.EqualTag _jspx_th_logic_005fequal_005f2 = (org.apache.struts.taglib.logic.EqualTag) _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.get(org.apache.struts.taglib.logic.EqualTag.class);
    boolean _jspx_th_logic_005fequal_005f2_reused = false;
    try {
      _jspx_th_logic_005fequal_005f2.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fequal_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fiterate_005f0);
      // /jsp/templates/PlatformTemplate.jsp(79,1265) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f2.setName("messageVO");
      // /jsp/templates/PlatformTemplate.jsp(79,1265) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f2.setProperty("type");
      // /jsp/templates/PlatformTemplate.jsp(79,1265) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fequal_005f2.setValue("ERROR");
      int _jspx_eval_logic_005fequal_005f2 = _jspx_th_logic_005fequal_005f2.doStartTag();
      if (_jspx_eval_logic_005fequal_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\t\t\t\t\t\t\t\t\t    \t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\t\t\t<i class=\"fa  fa-times-circle cs-ts-14\"></i>\t\t\t\t\t\t\t\t\t\t    \t\t\t");
          int evalDoAfterBody = _jspx_th_logic_005fequal_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fequal_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.reuse(_jspx_th_logic_005fequal_005f2);
      _jspx_th_logic_005fequal_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_logic_005fequal_005f2, _jsp_getInstanceManager(), _jspx_th_logic_005fequal_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsert_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insert
    org.apache.struts.tiles.taglib.InsertTag _jspx_th_tiles_005finsert_005f1 = (org.apache.struts.tiles.taglib.InsertTag) _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.get(org.apache.struts.tiles.taglib.InsertTag.class);
    boolean _jspx_th_tiles_005finsert_005f1_reused = false;
    try {
      _jspx_th_tiles_005finsert_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsert_005f1.setParent(null);
      // /jsp/templates/PlatformTemplate.jsp(82,11) name = attribute type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsert_005f1.setAttribute("app.body");
      int _jspx_eval_tiles_005finsert_005f1 = _jspx_th_tiles_005finsert_005f1.doStartTag();
      if (_jspx_th_tiles_005finsert_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftiles_005finsert_0026_005fattribute_005fnobody.reuse(_jspx_th_tiles_005finsert_005f1);
      _jspx_th_tiles_005finsert_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tiles_005finsert_005f1, _jsp_getInstanceManager(), _jspx_th_tiles_005finsert_005f1_reused);
    }
    return false;
  }
}
